name: road-gnn-models
channels:
  - defaults
dependencies:
  - python=3.6.13
  - numpy=1.19.2
  - pandas=1.1.5
  - matplotlib=3.3.4
  - scipy=1.5.4
  - jupyter=1.0.0
  - ipykernel=5.3.4
  - plotly=5.6.0
  - seaborn=0.11.2
  - pip:
      - absl-py==1.4.0
      - attrs==22.2.0
      - cached-property==1.5.2
      - cachetools==4.2.4
      - chardet==4.0.0
      - cycler==0.11.0
      - decorator==4.4.2
      - google-auth==2.22.0
      - networkx==2.5.1
      - numba==0.52.0
      - h5py==3.1.0
      - pyzmq==19.0.2
      - requests==2.25.1
      - scikit-learn==0.24.1
      - torch==1.10.2
      - torch-geometric==2.0.3
      - torch-geometric-temporal==0.54.0
      - torch-scatter==2.0.9
      - torch-sparse==0.6.12
      - tqdm==4.59.0